function one() {
  window.alert("The emperor penguin is the tallest and heaviest of all living penguin species and is endemic to Antarctica. The male and female are similar in plumage and size, reaching 100 cm in length and weighing from 22 to 45 kg. Wikipedia");


}

function two() {
  window.alert("The rockhopper penguins are three closely related taxa of crested penguins that have been traditionally treated as a single species and are sometimes split into three species. Not all experts agree on the classification of these penguins");
}

function three() {
  window.alert("The king penguin is the second largest species of penguin, smaller, but somewhat similar in appearance to the emperor penguin. There are two subspecies: A. p. patagonicus and A. p. halli; patagonicus is found in the South Atlantic and halli in the South Indian Ocean and at Macquarie Island. ");
}

function four() {
  window.alert("The Adélie penguin is a species of penguin common along the entire coast of the Antarctic continent, which is its only habitat. It is the most widely spread penguin species, as well as the most southerly distributed of all penguins, along with the emperor penguin. Wikipedia")}

function five() {
  window.alert("The chinstrap penguin is a species of penguin that inhabits a variety of islands and shores in the Southern Pacific and the Antarctic Oceans. Its name stems from the narrow black band under its head, which makes it appear as if it were wearing a black helmet, making it easy to identify")}
function six() {
  window.alert(" The gentoo penguin is a penguin species in the genus Pygoscelis, most closely related to the Adélie penguin and the chinstrap penguin. The earliest scientific description was made in 1781 by Johann Reinhold Forster with a type locality in the Falkland Islands. Wikipedia ");
}

function seven() {
  window.alert("The erect-crested penguin is a penguin endemic to the New Zealand region and only breeds on the Bounty and Antipodes Islands. It has black upper parts, white underparts and a yellow eye stripe and crest. It spends the winter at sea and little is known about its biology and breeding habit");
}